#!/usr/bin/env sh
set -eu

scriptdir=$(dirname -- "$(readlink -f -- "$0")")

# ANSI colors
clearformat='\033[0m' # clear formatting
orange='\033[0;33m'

info() {
    printf >&2 "%b%s%b\n" "$orange" "${*}" "$clearformat"
}

info "Running hook from $scriptdir"

util="$HOME"/src/ccb01200/git-util/target/debug/git-util

GIT_UTIL_DISALLOWED_STRINGS="foobarxyz" GIT_UTIL_USER_EMAIL="397636+ccb012100@users.noreply.github.com" "$util" hook pre-commit